# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "C:/Users/840\ G6/Desktop/24P3032_Muhammad_Maaz_Task_1.o"
LINKOBJ  = "C:/Users/840 G6/Desktop/24P3032_Muhammad_Maaz_Task_1.o"
LIBS     = -L"E:/C language/Dev-Cpp/MinGW64/lib" -L"E:/C language/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/C language/Dev-Cpp/MinGW64/include" -I"E:/C language/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/C language/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/C language/Dev-Cpp/MinGW64/include" -I"E:/C language/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/C language/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/C language/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Week 2 Lab.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"C:/Users/840\ G6/Desktop/24P3032_Muhammad_Maaz_Task_1.o": C:/Users/840\ G6/Desktop/24P3032_Muhammad_Maaz_Task_1.c
	$(CC) -c "C:/Users/840 G6/Desktop/24P3032_Muhammad_Maaz_Task_1.c" -o "C:/Users/840 G6/Desktop/24P3032_Muhammad_Maaz_Task_1.o" $(CFLAGS)
